// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Enumerate available serial ports (does not connect). */
	listPorts: () => typedError<PortInfoDto[], string>(__TAURI_INVOKE("list_ports")),
	/**
	 *  Connect to an ECU (simulator or serial).
	 * 
	 *  The owner emits `ConnectionStateEvent` transitions over IPC as the
	 *  connection progresses. Resolves `Ok(())` once the handshake succeeds.
	 */
	connect: (source: ConnectSource) => typedError<null, string>(__TAURI_INVOKE("connect", { source })),
	/**  Disconnect from the ECU; the owner emits `Disconnected`. */
	disconnect: () => typedError<null, string>(__TAURI_INVOKE("disconnect")),
	/**
	 *  Simulator-only: drop the link and drive the reconnect loop. The owner
	 *  emits `Reconnecting{attempt}` states until `Connected` or `Failed`, and
	 *  re-reads the tune when the reconnect detected an ECU reboot.
	 */
	simulateLinkDrop: () => typedError<null, string>(__TAURI_INVOKE("simulate_link_drop")),
	/**
	 *  Return the parsed firmware definition (menus, dialogs, constants, …) for
	 *  the frontend to render the data-driven UI against.
	 */
	getDefinition: () => typedError<DefinitionDto, string>(__TAURI_INVOKE("get_definition")),
	/**
	 *  Read all declared pages from the ECU into a fresh tune. The owner emits
	 *  the (clean) dirty state.
	 */
	loadTune: () => typedError<null, string>(__TAURI_INVOKE("load_tune")),
	/**  Read the current physical values of the named constants (for field render). */
	getValues: (names: string[]) => typedError<Value[], string>(__TAURI_INVOKE("get_values", { names })),
	/**
	 *  Set a constant and write the changed bytes live to the ECU. The owner
	 *  emits the new dirty state on success.
	 */
	setValue: (name: string, value: Value) => typedError<null, string>(__TAURI_INVOKE("set_value", { name, value })),
	/**  Write individual cells of an array constant (a table-editor gesture). */
	setCells: (name: string, cells: CellEditDto[]) => typedError<null, string>(__TAURI_INVOKE("set_cells", { name, cells })),
	/**  Burn every dirty page to flash. The owner emits the cleared dirty state. */
	burnTune: () => typedError<null, string>(__TAURI_INVOKE("burn_tune")),
	/**  Undo the most recent edit, writing the reverted bytes to the ECU. */
	undoTune: () => typedError<null, string>(__TAURI_INVOKE("undo_tune")),
	/**  Redo the most recently undone edit, writing the re-applied bytes to the ECU. */
	redoTune: () => typedError<null, string>(__TAURI_INVOKE("redo_tune")),
	/**
	 *  Evaluate `visible`/`enable` expressions against the current tune values.
	 *  Fails open (a broken expression yields `true`).
	 */
	evalConditions: (exprs: string[]) => typedError<boolean[], string>(__TAURI_INVOKE("eval_conditions", { exprs })),
	/**  Snapshot the current tune as the diff/merge baseline (the "other" side). */
	snapshotTune: () => typedError<null, string>(__TAURI_INVOKE("snapshot_tune")),
	/**
	 *  Diff the current tune against the snapshot baseline taken by
	 *  `snapshot_tune`.
	 */
	diffTune: () => typedError<FieldDiffDto[], string>(__TAURI_INVOKE("diff_tune")),
	/**
	 *  Merge the picked constants from the snapshot baseline into the current
	 *  tune, writing each accepted pick live to the ECU.
	 * 
	 *  The owner emits the tune's *actual* dirty state after the merge attempt —
	 *  regardless of `Ok`/`Err` — because a merge can abort mid-batch after
	 *  earlier picks already committed (M2 behavior, preserved).
	 */
	mergeTune: (picks: string[]) => typedError<null, string>(__TAURI_INVOKE("merge_tune", { picks })),
	/**
	 *  Start the 25 Hz realtime poll loop (frames are emitted coalesced to
	 *  ≤30 Hz as `RealtimeFrameEvent`s).
	 */
	startRealtime: () => typedError<null, string>(__TAURI_INVOKE("start_realtime")),
	/**  Stop the realtime poll loop. */
	stopRealtime: () => typedError<null, string>(__TAURI_INVOKE("stop_realtime")),
	/**  Persist the dashboard layout JSON to the app config dir. */
	saveLayout: (json: string) => typedError<null, string>(__TAURI_INVOKE("save_layout", { json })),
	/**  Load the persisted dashboard layout JSON; `None` when never saved. */
	loadLayout: () => typedError<string | null, string>(__TAURI_INVOKE("load_layout")),
};

/** Events */
export const events = {
	connectionStateEvent: makeEvent<ConnectionStateEvent>("connection-state-event"),
	heartbeat: makeEvent<Heartbeat>("heartbeat"),
	realtimeFrameEvent: makeEvent<RealtimeFrameEvent>("realtime-frame-event"),
	tuneDirtyEvent: makeEvent<TuneDirtyEvent>("tune-dirty-event"),
};

/* Types */
export type AppInfo = {
	name: string,
	version: string,
};

/**
 *  Curve axis bounds when literal (an `{expr}` bound resolves to `None` —
 *  the frontend falls back to data extents).
 */
export type AxisDto = {
	min: number | null,
	max: number | null,
	divisions: number,
};

/**  IPC projection of [`opentune_model::CellDiff`]. */
export type CellDiffDto = {
	index: number,
	a: number | null,
	b: number | null,
};

/**
 *  One flat cell edit for [`crate::owner::Command::SetCells`] — command
 *  *input*, hence `Deserialize` in addition to the usual `Serialize`.
 */
export type CellEditDto = {
	index: number,
	value: number | null,
};

/**  Which ECU to connect to; deserialized from the frontend command payload. */
export type ConnectSource = 
/**  Built-in simulator. */
{ type: "simulator"; 
/**  Override INI path; `None` → load bundled sample. */
ini_path: string | null } | 
/**  Real serial port. */
{ type: "serial"; port_name: string; 
/**  INI path (required for serial). */
ini_path: string };

/**
 *  IPC-serialisable mirror of [`opentune_protocol::ConnectionState`].
 * 
 *  `tauri-specta` requires `specta::Type` on every emitted event type.
 *  `ConnectionState` lives in the `protocol` crate which intentionally has
 *  no dependency on `specta`, so we mirror only the fields the UI needs.
 *  The Rust → TS direction is write-only (backend emits, frontend listens).
 * 
 *  # Variants
 *  - `Disconnected` — no active link.
 *  - `Connecting` — transport opening / handshake in progress.
 *  - `Connected` — fully identified; includes the firmware signature.
 *  - `Reconnecting` — link was lost; retry in progress; `attempt` is 1-based.
 *  - `Failed` — gave up; `reason` is a human-readable diagnostic.
 */
export type ConnectionStateEvent = { type: "disconnected" } | { type: "connecting" } | { type: "connected"; 
/**  The firmware signature string reported by the ECU. */
signature: string; 
/**  The human-readable firmware version string (may be empty). */
version: string } | { type: "reconnecting"; 
/**  1-based retry count so the UI can show progress. */
attempt: number } | { type: "failed"; 
/**  Diagnostic string; never expose internal paths or hardware details. */
reason: string };

/**  A constant's UI metadata (no byte layout). */
export type ConstantDto = {
	name: string,
	units: string,
	/**  Decimal digits to display for scalar values. */
	digits: number,
	/**
	 *  Lower bound, when a literal (an expression bound resolves to `None` — the
	 *  backend still range-checks on write).
	 */
	low: number | null,
	/**  Upper bound, when a literal. */
	high: number | null,
	kind: ConstantKindDto,
};

/**  A constant's interpretation kind, trimmed for the UI. */
export type ConstantKindDto = 
/**  A single editable scalar. */
"Scalar" | 
/**  An enum-like selector with named options. */
({ Bits: {
	options: string[],
} }) & { Array?: never } | 
/**  A fixed-shape array/table. */
({ Array: {
	rows: number,
	cols: number,
} }) & { Bits?: never } | 
/**  A fixed-length text field. */
"Text";

/**  A curve editor definition (M4). */
export type CurveDto = {
	name: string,
	title: string,
	column_labels: string[],
	x_axis: AxisDto | null,
	y_axis: AxisDto | null,
	x_bins: string,
	x_channel: string,
	y_bins: string,
	gauge: string,
};

/**  The UI-facing projection of a [`Definition`]. */
export type DefinitionDto = {
	/**  The firmware signature, for display. */
	signature: string,
	/**  Top-level menus. */
	menus: MenuDto[],
	/**  Dialogs referenced by menu items and panels. */
	dialogs: DialogDto[],
	/**  Constants referenced by dialog fields, indexed by name on the frontend. */
	constants: ConstantDto[],
	/**  Table editors (rendered as a minimal grid in M2; full editor is M4). */
	tables: TableDto[],
	/**  Curve (2-D) editors (M4). */
	curves: CurveDto[],
	/**  `[GaugeConfigurations]` entries backing the dashboard (M3). */
	gauges: GaugeDto[],
	/**  `[FrontPage]` — the default dashboard layout (M3). */
	frontpage: FrontPageDto,
};

/**  A dialog and its fields. */
export type DialogDto = {
	name: string,
	title: string,
	fields: FieldDto[],
};

/**
 *  IPC projection of [`opentune_model::FieldDiff`] — identical shape, but
 *  (transitively, via [`CellDiffDto`]) narrows the `usize` cell index to
 *  `u32`, since the pinned `specta-typescript` forbids exporting `usize`.
 */
export type FieldDiffDto = {
	name: string,
	a: Value,
	b: Value,
	cells: CellDiffDto[],
};

/**
 *  A single field with its raw visibility/enable expressions (evaluated by the
 *  backend `eval_conditions` command — one source of truth, no TS port).
 */
export type FieldDto = {
	kind: FieldKindDto,
	visible: string | null,
	enable: string | null,
};

/**  The kind of a field (mirrors `FieldKind`, externally tagged). */
export type FieldKindDto = 
/**  Bound to a named constant. */
({ Constant: string }) & { Label?: never; Panel?: never } | 
/**  A nested panel referencing another dialog by name. */
({ Panel: string }) & { Constant?: never; Label?: never } | 
/**  A static label. */
({ Label: string }) & { Constant?: never; Panel?: never } | 
/**  A layout spacer. */
"Gap";

/**  `[FrontPage]` — the default dashboard layout. */
export type FrontPageDto = {
	/**  `gauge1..gauge8` → gauge names, in slot order. */
	gauge_slots: string[],
	/**  Boolean indicator lamps shown alongside the gauges. */
	indicators: IndicatorDto[],
};

/**
 *  A gauge's display rules (title, unit label, thresholds, digits) — the UI
 *  projection of [`GaugeDef`]. Numeric bounds follow the [`ConstantDto`]
 *  convention: a literal projects to `Some`, an `{ expr }` bound to `None`
 *  (the gauge falls back to a neutral zone for `None` thresholds).
 */
export type GaugeDto = {
	/**  Gauge id referenced by `FrontPageDto::gauge_slots`. */
	name: string,
	/**  The output-channel name it displays (keys the realtime frame map). */
	channel: string,
	title: string,
	/**  The unit label shown in the UI (e.g. "RPM", "kPa"). */
	units: string,
	low: number | null,
	high: number | null,
	lo_danger: number | null,
	lo_warn: number | null,
	hi_warn: number | null,
	hi_danger: number | null,
	/**  Decimal digits for the live value readout. */
	value_digits: number,
	/**  Decimal digits for scale labels. */
	label_digits: number,
	/**  `gaugeCategory`, for grouping menus. */
	category: string,
};

export type Heartbeat = {
	seq: number,
};

/**  One `[FrontPage]` `indicator` entry (colors are named colors, verbatim). */
export type IndicatorDto = {
	/**  Bare bit-channel name or comparison; evaluated against realtime frames. */
	expr: string,
	off_label: string,
	on_label: string,
	off_bg: string,
	off_fg: string,
	on_bg: string,
	on_fg: string,
};

/**  A top-level menu. */
export type MenuDto = {
	label: string,
	items: MenuItemDto[],
};

/**  A menu entry that opens a dialog by name. */
export type MenuItemDto = {
	label: string,
	dialog: string,
};

/**  Port information for the frontend UI. */
export type PortInfoDto = {
	name: string,
	vid: number | null,
	pid: number | null,
	product: string | null,
};

/**
 *  The M3 realtime dashboard frame payload, emitted at up to ~30 Hz.
 * 
 *  Registered in `collect_events!` (`lib.rs`) alongside the
 *  `start_realtime`/`stop_realtime` commands. The owner poll loop emits it,
 *  coalesced to ≤30 Hz, for as long as realtime is armed — arming persists
 *  across a link drop, so frames resume automatically after recovery.
 */
export type RealtimeFrameEvent = {
	/**  (channel name, physical value) pairs — the full decoded frame, ≤30 Hz. */
	channels: ([string, number | null])[],
};

/**  A table editor definition (bin/cell constant references). */
export type TableDto = {
	name: string,
	title: string,
	page: number,
	x_bins: string,
	/**  Output channel driving the live X cursor ("" when the INI names none). */
	x_channel: string,
	y_bins: string,
	y_channel: string,
	z: string,
	xy_labels: string[],
	up_down_label: string[],
	help: string,
};

/**
 *  Emitted whenever the in-memory [`Tune`](opentune_model::Tune) dirty state
 *  changes — after a `set_value`, `undo`, `redo`, or `burn`. Drives the
 *  "modified, not burned" badge: `dirty == true` means RAM diverges from flash.
 * 
 *  The backend is the single source of truth; the frontend never computes
 *  dirtiness itself, it just reflects the last event it received.
 */
export type TuneDirtyEvent = {
	/**  Whether any page has unburned edits. */
	dirty: boolean,
	/**  The page numbers with unburned edits, ascending. Empty when clean. */
	dirty_pages: number[],
};

/**
 *  A decoded constant value, in its physical (already scaled) representation.
 * 
 *  Derives `serde::Serialize` + `serde::Deserialize` + `specta::Type`: the
 *  frontend both receives values read from a [`Tune`](crate::Tune) and sends
 *  them back over IPC (the `set_value` command), so `Value` crosses the seam
 *  in both directions. It stays externally tagged (`{ "Scalar": 12.5 }`),
 *  which is the shape `specta` generates for the TS union.
 */
export type Value = 
/**  A single physical scalar (already `raw * scale + translate`). */
({ Scalar: number | null }) & { Array?: never; Enum?: never; Text?: never } | 
/**  A physical array/table of scalars, row-major. */
({ Array: (number | null)[] }) & { Enum?: never; Scalar?: never; Text?: never } | 
/**  A bitfield/enum's raw selected index (see `ConstantKind::Bits::options`). */
({ Enum: number }) & { Array?: never; Scalar?: never; Text?: never } | 
/**  A fixed-length text value. */
({ Text: string }) & { Array?: never; Enum?: never; Scalar?: never };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

